version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    networks:
      - onlyoffice
    expose:
      - '5432'
    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data
    env_file:
      - db.env
  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    networks:
      - onlyoffice
    volumes:
      - app_data:/var/www/html
      - /data/nextcloud/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud/config:/var/www/html/config
      - /data:/data

    env_file:
      - db.env
    depends_on:
      - db
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 3080:80
      - 3443:443
    networks:
      - onlyoffice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
